#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

#export IMPORTANT_ENVIRONMENT_VARIABLE=value

# Assume only one file
jar_file="$(
    ls -1 "${SNAP}"/Bytecode-Viewer-*.jar \
        | head --lines=1
)"

# Finally run the next part of the command chain
exec \
    java \
        -jar \
        "${jar_file}" \
        "${@}"
